### ISSUE TITLE
Create group concept

### ISSUE THREAD

**Issue by cafca** [cafca/souma#21]
see https://trello.com/card/knowledge-management-in-groups-topics/5193c932d12791b965000011/5
- General approach: Develop minimal group functionality first with modularity in mind, simultaneously develop more sophisticated concept of groups and finally extend minimal model in direction of that concept
- Minimal group functionality:
  - Creating, browsing group page, posting to group page
- Approaches at defining extended group concept:
  - What are we using ourself? (Study project)
  - What are intuitive functionalities?
  - Get/invite users into group, assign roles to group members, Wiki, votes / decision making tools
  - Implementing functionality in analogy to paper on leading self-managed groups
  - What do groups need to solve specific problems?
- Performance measurement of group functionality
  - What are we measuring? How?
  - Intra- or inter-group measurement
  - Qualitative measurement: Surveys
  - Quantitative measurement: Group coherence, solving a specific task, etc.
- Outlook
  - Deleting groups
  - Administration models (dictator, democratic, representative, etc.)

Todo:
- [ ] Put content from here to wiki https://github.com/ciex/souma/wiki/Collaboration-and-Groups
- [ ] Assess our own organisational structures #82
- [x] Implement minimal group functionality #83
- [x] Look at paper (above) and see whether we can derive functionality needed for groups from it
- [ ] Sketch a concept for group knowledge management #53

**Comment by cafca** [comment]
Will meet with Ash on Monday to talk about knowledge management and groups in general

**Comment by cafca** [comment]
Meeting on 19 Dec 2013 / 2.30pm-4pm
Attendance: @cartisan @ciex @Trami 
- Defined status quo
- Wrote task description
- Linked related issues
